name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '5 8 15 * *'

jobs:
  test:
    name: "Run Unit & Integration Tests"
    uses: eclipse-pass/main/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      run_acceptance_tests: false