name: Publish Release

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
      nextversion:
        description: 'Next dev version'
        required: true

jobs:
  release:
    uses: eclipse-pass/main/.github/workflows/release.yml@main
    secrets: inherit
    with:
      releaseversion: ${{ inputs.releaseversion }}
      nextversion: ${{ inputs.nextversion}}
      images: ghcr.io/eclipse-pass/deposit-services-core ghcr.io/eclipse-pass/pass-notification-service ghcr.io/eclipse-pass/jhu-grant-loader ghcr.io/eclipse-pass/pass-journal-loader ghcr.io/eclipse-pass/pass-nihms-loader ghcr.io/eclipse-pass/pass-nihms-token-refresh
