name: Publish SNAPSHOT

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  snapshot:
    uses: eclipse-pass/main/.github/workflows/snapshot.yml@main
    secrets: inherit
    with:
      images: ghcr.io/eclipse-pass/deposit-services-core ghcr.io/eclipse-pass/pass-notification-service ghcr.io/eclipse-pass/jhu-grant-loader ghcr.io/eclipse-pass/pass-journal-loader ghcr.io/eclipse-pass/pass-nihms-loader
