name: Publish SNAPSHOT

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  snapshot:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: eclipse-pass/main/.github/workflows/snapshot.yml@1089-test-ci-yml-NO-MERGE-DELETE-AFTER-TESTING
    secrets: inherit
    with:
      images: ghcr.io/eclipse-pass/deposit-services-core ghcr.io/eclipse-pass/pass-notification-service ghcr.io/eclipse-pass/jhu-grant-loader ghcr.io/eclipse-pass/pass-journal-loader ghcr.io/eclipse-pass/pass-nihms-loader ghcr.io/eclipse-pass/pass-nihms-token-refresh
